on:
  schedule:
    - cron: '0 8 * * 6'

name: Oracle

jobs:
  Oracle-test:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}
    env:
      STATUS: 0
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

      DBMS: 'oracle'

      USER: ${{ secrets.ORACLE_USER }}
      PASSWORD: ${{ secrets.ORACLE_PASSWORD }}
      SERVER: ${{ secrets.ORACLE_SERVER }}
      
      CDM_SCHEMA: ${{ secrets.ORACLE_CDM_SCHEMA }}
      RESULT_SCHEMA: ${{ secrets.ORACLE_RESULT_SCHEMA  }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true
          extra-repositories: 'https://OHDSI.github.io/drat'

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          dependencies: '"all"'

      - name: Install TreatmentPatterns
        run: R CMD INSTALL --with-keep.source --no-multiarch ./

      - name: Run test-database.R
        run: |
          Rscript -e 'testthat::test_file(
            path = "./extras/database_tests/CDMConnector-jdbc.R",
            reporter = c("summary", "fail"),
            package = "TreatmentPatterns"
          )'